version: '3.7'

services:
  php:
    build:
      context: ../
      dockerfile: infrastructure/DockerFile
    volumes:
      - ../code:/var/www/html
    networks:
      - my_network

  nginx:
    image: nginx:1.24.0
    ports:
      - "80:80"
    volumes:
      - ./images/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../code:/var/www/html:ro
    networks:
      - my_network

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: ApiBooksDBMongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mongo_data: